version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4569:4569"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      # uncomment bellow if you want to cache runtime installations and all config
      # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgis_db:
    build:
      context: ./docker/postgis
      dockerfile: Dockerfile
    restart: always
    environment:
      ALLOW_IP_RANGE: "0.0.0.0/0"
      POSTGRES_DB: kvarovi
      POSTGRES_USER: dbuser_HERE
      POSTGRES_PASSWORD: dbpassword_HERE
    ports:
      - 5432:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./docker/postgis/input_data:/input_data

volumes:
  postgis_data:
