AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Beograd Telegram Bots

Globals:
  Function:
    Timeout: 100
    MemorySize: 128
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:38"

Resources:
  RawDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  DataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  ChatPreferences:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: chat_preferences
      PrimaryKey:
        Name: chat_id
        Type: Number

  ElectroCollector:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: electro_collector
      BuildArchitecture: x86_64
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 hour)"
            RetryPolicy:
              MaximumRetryAttempts: 3
      Environment:
        Variables:
          RAW_DATA_TABLE_NAME: !Ref RawDataTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RawDataTable
        - CloudWatchLambdaInsightsExecutionRolePolicy

  ElectroParser:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: electro_parser
      BuildArchitecture: x86_64
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 hour)"
            RetryPolicy:
              MaximumRetryAttempts: 3
      Environment:
        Variables:
          RAW_DATA_TABLE_NAME: !Ref RawDataTable
          DATA_TABLE_NAME: !Ref DataTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RawDataTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
        - CloudWatchLambdaInsightsExecutionRolePolicy

Outputs:
  ElectroCollector:
    Description: "Collect electro time tables"
    Value: !GetAtt ElectroCollector.Arn
  RawDataTable:
    Description: "DynamoDB table name"
    Value: !GetAtt RawDataTable.Arn
  DataTable:
    Description: "DynamoDB table name"
    Value: !GetAtt DataTable.Arn
  ChatPreferences:
    Description: "DynamoDB table name"
    Value: !GetAtt ChatPreferences.Arn
