[package]
name = "electricity"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.15", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
tokio-cron-scheduler = "0.9.4"
component = "0.1.0"
scraper = "0.16.0"
aws-config = "0.55.2"
aws-sdk-dynamodb = "0.27.0"
uuid = "1.3.2"
