[package]
name = "electricity"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.15", features = ["full"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls"] }
serde = { version = "1", features = ["derive"] }
lambda_runtime = "0.8"
serde_json = "1"
