// This file is generated by build.rs. Do not edit it manually!

use crate::Street;


pub fn get_streets_list() -> Vec<Street> {
    let streets: [Street; 10] = [
        Street {
            street_name: String::from("1. novembra"),
            old_street_name: Some(String::from("")),
            municipality: String::from("zvezdara"),
            settlement: String::from("beograd"),
            settlement_part: String::from("beograd"),
            si_list: Some(String::from("2018/119")),
        },
        Street {
            street_name: String::from("11. novembra"),
            old_street_name: Some(String::from("")),
            municipality: String::from("mladenovac"),
            settlement: String::from("mladenovac (varoŠ)"),
            settlement_part: String::from("mladenovac (varoŠ)"),
            si_list: Some(String::from("")),
        },
        Street {
            street_name: String::from("15. februara"),
            old_street_name: Some(String::from("")),
            municipality: String::from("mladenovac"),
            settlement: String::from("meĐuluŽje"),
            settlement_part: String::from("meĐuluŽje"),
            si_list: Some(String::from("")),
        },
        Street {
            street_name: String::from("15. februara"),
            old_street_name: Some(String::from("")),
            municipality: String::from("zvezdara"),
            settlement: String::from("beograd"),
            settlement_part: String::from("bg-m m lug"),
            si_list: Some(String::from("2018/119")),
        },
        Street {
            street_name: String::from("16. aprila"),
            old_street_name: Some(String::from("")),
            municipality: String::from("mladenovac"),
            settlement: String::from("meĐuluŽje"),
            settlement_part: String::from("meĐuluŽje"),
            si_list: Some(String::from("")),
        },
        Street {
            street_name: String::from("16. aprila"),
            old_street_name: Some(String::from("")),
            municipality: String::from("palilula"),
            settlement: String::from("beograd"),
            settlement_part: String::from("ovČa"),
            si_list: Some(String::from("2019/013")),
        },
        Street {
            street_name: String::from("19. aprila"),
            old_street_name: Some(String::from("")),
            municipality: String::from("rakovica"),
            settlement: String::from("beograd"),
            settlement_part: String::from("beograd"),
            si_list: Some(String::from("")),
        },
        Street {
            street_name: String::from("20. oktobra"),
            old_street_name: Some(String::from("")),
            municipality: String::from("mladenovac"),
            settlement: String::from("mladenovac (varoŠ)"),
            settlement_part: String::from("mladenovac (varoŠ)"),
            si_list: Some(String::from("")),
        },
        Street {
            street_name: String::from("28. juna"),
            old_street_name: Some(String::from("mokroluŠka nova")),
            municipality: String::from("voŽdovac"),
            settlement: String::from("beograd"),
            settlement_part: String::from("beograd"),
            si_list: Some(String::from("2018/119")),
        },
        Street {
            street_name: String::from("30.maja"),
            old_street_name: Some(String::from("")),
            municipality: String::from("novi beograd"),
            settlement: String::from("beograd"),
            settlement_part: String::from("beograd"),
            si_list: Some(String::from("2019/066")),
        },
    ];

    streets.to_vec()
}

