[package]
name = "bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
teloxide-core = "0.9.1"
dotenv = "0.15.0"
anyhow = "1.0.44"
redis = { version = "0.23.0", features = ["tokio-comp"] }
rust-i18n = { version = "2.0.0"}
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres" ] }
async-trait = { version = "0.1.72"}
