[package]
name = "beograd_streets"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[build-dependencies]
csv = { version = "1.2.1"}
serde = { version = "1.0.130", features = ["derive"] }
anyhow = { version = "1.0.42" }