permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
name: check
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          toolchain: stable
      - name: rustfmt
        run: cargo fmt --all -- --check

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  clippy:
    runs-on: ubuntu-latest
    name: stable / clippy
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets